#### Predict Employee Resignation (Attrition)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Dataset
data = {
    "EmployeeID": [
        101,102,103,104,105,106,107,108,109,110,
        111,112,113,114,115,116,117,118,119,120
    ],

    "Age": [
        24,42,31,29,50,37,26,45,33,39,
        28,41,35,30,47,27,38,32,44,36
    ],

    "YearsAtCompany": [
        1,12,5,3,20,9,2,15,6,11,
        4,13,8,5,18,2,10,7,16,9
    ],

    "MonthlyIncome": [
        3500,9800,5400,4200,15000,
        8600,3900,12000,6100,9100,
        4700,10400,7300,5600,13800,
        4100,8900,6500,12600,7800
    ],

    "Overtime": [
        "Yes","No","Yes","Yes","No",
        "No","Yes","No","Yes","No",
        "Yes","No","No","Yes","No",
        "Yes","No","Yes","No","No"
    ],

    "BusinessTravel": [
        "Frequently","Rarely","Frequently","Rarely","Never",
        "Rarely","Frequently","Never","Frequently","Rarely",
        "Frequently","Never","Rarely","Frequently","Never",
        "Frequently","Rarely","Frequently","Never","Rarely"
    ],

    "JobRole": [
        "Developer","Manager","Tester","Developer","Director",
        "Manager","Support","Director","Developer","Manager",
        "Tester","Director","Developer","Support","Director",
        "Tester","Manager","Developer","Director","Support"
    ],

    "WorkLifeBalance": [
        "Poor","Excellent","Average","Poor","Excellent",
        "Good","Poor","Excellent","Average","Good",
        "Poor","Excellent","Good","Average","Excellent",
        "Poor","Good","Average","Excellent","Good"
    ],

    "JobSatisfaction": [
        2,5,3,2,5,
        4,2,5,3,4,
        2,5,4,3,5,
        2,4,3,5,4
    ],

    "PerformanceRating": [
        3,5,4,3,5,
        4,3,5,4,4,
        3,5,4,3,5,
        3,4,4,5,4
    ],

    "ProjectsHandled": [
        2,7,4,3,10,
        6,2,9,5,6,
        3,8,5,4,9,
        2,6,5,10,6
    ],

    "RemoteWork": [
        "Yes","No","Yes","Yes","No",
        "No","Yes","No","Yes","No",
        "Yes","No","No","Yes","No",
        "Yes","No","Yes","No","No"
    ],

    "Resigned": [
        1,0,1,1,0,
        0,1,0,1,0,
        1,0,0,1,0,
        1,0,1,0,0
    ]
}

In [3]:
# Converting into table
df = pd.DataFrame(data)
df

,EmployeeID,Age,YearsAtCompany,MonthlyIncome,Overtime,BusinessTravel,JobRole,WorkLifeBalance,JobSatisfaction,PerformanceRating,ProjectsHandled,RemoteWork,Resigned
0,101,24,1,3500,Yes,Frequently,Developer,Poor,2,3,2,Yes,1
1,102,42,12,9800,No,Rarely,Manager,Excellent,5,5,7,No,0
2,103,31,5,5400,Yes,Frequently,Tester,Average,3,4,4,Yes,1
3,104,29,3,4200,Yes,Rarely,Developer,Poor,2,3,3,Yes,1
4,105,50,20,15000,No,Never,Director,Excellent,5,5,10,No,0
5,106,37,9,8600,No,Rarely,Manager,Good,4,4,6,No,0
6,107,26,2,3900,Yes,Frequently,Support,Poor,2,3,2,Yes,1
7,108,45,15,12000,No,Never,Director,Excellent,5,5,9,No,0
8,109,33,6,6100,Yes,Frequently,Developer,Average,3,4,5,Yes,1
9,110,39,11,9100,No,Rarely,Manager,Good,4,4,6,No,0
10,111,28,4,4700,Yes,Frequently,Tester,Poor,2,3,3,Yes,1
11,112,41,13,10400,No,Never,Director,Excellent,5,5,8,No,0
12,113,35,8,7300,No,Rarely,Developer,Good,4,4,5,No,0
13,114,30,5,5600,Yes,Frequently,Support,Average,3,3,4,Yes,1
14,115,47,18,13800,No,Never,Director,Excellent,5,5,9,No,0
15,116,27,2,4100,Yes,Frequently,Tester,Poor,2,3,2,Yes,1
16,117,38,10,8900,No,Rarely,Manager,Good,4,4,6,No,0
17,118,32,7,6500,Yes,Frequently,Developer,Average,3,4,5,Yes,1
18,119,44,16,12600,No,Never,Director,Excellent,5,5,10,No,0
19,120,36,9,7800,No,Rarely,Support,Good,4,4,6,No,0

In [4]:
# Dropping identifier column
new_df = df.drop(columns=['EmployeeID'])
new_df

,Age,YearsAtCompany,MonthlyIncome,Overtime,BusinessTravel,JobRole,WorkLifeBalance,JobSatisfaction,PerformanceRating,ProjectsHandled,RemoteWork,Resigned
0,24,1,3500,Yes,Frequently,Developer,Poor,2,3,2,Yes,1
1,42,12,9800,No,Rarely,Manager,Excellent,5,5,7,No,0
2,31,5,5400,Yes,Frequently,Tester,Average,3,4,4,Yes,1
3,29,3,4200,Yes,Rarely,Developer,Poor,2,3,3,Yes,1
4,50,20,15000,No,Never,Director,Excellent,5,5,10,No,0
5,37,9,8600,No,Rarely,Manager,Good,4,4,6,No,0
6,26,2,3900,Yes,Frequently,Support,Poor,2,3,2,Yes,1
7,45,15,12000,No,Never,Director,Excellent,5,5,9,No,0
8,33,6,6100,Yes,Frequently,Developer,Average,3,4,5,Yes,1
9,39,11,9100,No,Rarely,Manager,Good,4,4,6,No,0
10,28,4,4700,Yes,Frequently,Tester,Poor,2,3,3,Yes,1
11,41,13,10400,No,Never,Director,Excellent,5,5,8,No,0
12,35,8,7300,No,Rarely,Developer,Good,4,4,5,No,0
13,30,5,5600,Yes,Frequently,Support,Average,3,3,4,Yes,1
14,47,18,13800,No,Never,Director,Excellent,5,5,9,No,0
15,27,2,4100,Yes,Frequently,Tester,Poor,2,3,2,Yes,1
16,38,10,8900,No,Rarely,Manager,Good,4,4,6,No,0
17,32,7,6500,Yes,Frequently,Developer,Average,3,4,5,Yes,1
18,44,16,12600,No,Never,Director,Excellent,5,5,10,No,0
19,36,9,7800,No,Rarely,Support,Good,4,4,6,No,0

In [ ]:
# Encoding categorical variables

# Binary Encoding
new_df.replace({
    "Yes":1,
    "No":0
}, inplace=True)

# Ordinal Encoding
new_df["WorkLifeBalance"] = new_df["WorkLifeBalance"].replace({
    "Poor":0,
    "Average":1,
    "Good":2,
    "Excellent":3
})

# One-Hot Encoding
new_df = pd.get_dummies(
    new_df,
    columns=[
        "BusinessTravel",
        "JobRole"
    ],
    drop_first=True,
    dtype=int
)

In [6]:
new_df

,Age,YearsAtCompany,MonthlyIncome,Overtime,WorkLifeBalance,JobSatisfaction,PerformanceRating,ProjectsHandled,RemoteWork,Resigned,BusinessTravel_Never,BusinessTravel_Rarely,JobRole_Director,JobRole_Manager,JobRole_Support,JobRole_Tester
0,24,1,3500,1,0,2,3,2,1,1,0,0,0,0,0,0
1,42,12,9800,0,3,5,5,7,0,0,0,1,0,1,0,0
2,31,5,5400,1,1,3,4,4,1,1,0,0,0,0,0,1
3,29,3,4200,1,0,2,3,3,1,1,0,1,0,0,0,0
4,50,20,15000,0,3,5,5,10,0,0,1,0,1,0,0,0
5,37,9,8600,0,2,4,4,6,0,0,0,1,0,1,0,0
6,26,2,3900,1,0,2,3,2,1,1,0,0,0,0,1,0
7,45,15,12000,0,3,5,5,9,0,0,1,0,1,0,0,0
8,33,6,6100,1,1,3,4,5,1,1,0,0,0,0,0,0
9,39,11,9100,0,2,4,4,6,0,0,0,1,0,1,0,0
10,28,4,4700,1,0,2,3,3,1,1,0,0,0,0,0,1
11,41,13,10400,0,3,5,5,8,0,0,1,0,1,0,0,0
12,35,8,7300,0,2,4,4,5,0,0,0,1,0,0,0,0
13,30,5,5600,1,1,3,3,4,1,1,0,0,0,0,1,0
14,47,18,13800,0,3,5,5,9,0,0,1,0,1,0,0,0
15,27,2,4100,1,0,2,3,2,1,1,0,0,0,0,0,1
16,38,10,8900,0,2,4,4,6,0,0,0,1,0,1,0,0
17,32,7,6500,1,1,3,4,5,1,1,0,0,0,0,0,0
18,44,16,12600,0,3,5,5,10,0,0,1,0,1,0,0,0
19,36,9,7800,0,2,4,4,6,0,0,0,1,0,0,1,0

In [7]:
X = new_df.drop("Resigned", axis=1).values

y = new_df["Resigned"].values

In [8]:
# Normalize the features
mean = X.mean()
std = X.std()
X_scale = (X-mean)/std

In [9]:
# Initialize before training

m,n = X_scale.shape  # m -> number of samples, n -> number of features
weights = np.zeros(n)
bias = 0

learning_rate = 0.01
epochs = 3000

In [10]:
# Sigmoid function

def sigmoid(z):
    return 1/(1+np.exp(-z))

In [11]:
# Logistic Regression Algorithm

for epoch in range(epochs):
    # Forward pass
    z = np.dot(X_scale,weights) + bias
    prediction = sigmoid(z)

    # Loss Function
    loss = -np.mean(
        y * np.log(prediction + 1e-15)
        +
        (1-y) *
        np.log(
            1-prediction + 1e-15
        )
    )

    # Gradients
    dw = (1/m) * np.dot(X_scale.T, (prediction-y))
    db = (1/m) * np.sum(prediction-y)

    # Update
    weights -= learning_rate*dw
    bias -= learning_rate*db

    # Print Loss
    if epoch % 500 == 0:
        print(
            f"Epoch {epoch}, Loss = {loss:.4f}"
        )

print("\nTraining Completed")

print("\nWeights", weights)
print("\nBias", bias)

Epoch 0, Loss = 0.6931
Epoch 500, Loss = 0.4630
Epoch 1000, Loss = 0.3771
Epoch 1500, Loss = 0.3224
Epoch 2000, Loss = 0.2847
Epoch 2500, Loss = 0.2571

Training Completed

Weights [-0.50430614 -0.52463625 -1.38277169 -0.51713791 -0.5215352  -0.51959334
 -0.51749317 -0.52028171 -0.51713791 -0.51985154 -0.52045968 -0.51985154
 -0.52018786 -0.519262   -0.51878216]

Bias 2.105387755273298

In [12]:
# Computing predicted probabilities after training
z1 = np.dot(X_scale, weights) + bias
pred1 = sigmoid(z)

In [13]:
# Seperate the probabilities into classes of 0 and 1
predicted_classes = (
    pred1 >= 0.5
).astype(int)

In [14]:
# Calculating accuracy of the model
correct = np.sum(predicted_classes == y)

acc = correct/len(y)
print("Accuracy of the model is: ",acc)

Accuracy of the model is:  1.0